services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                user: laravel
                uid: 1000
        image: ryrtemplate
        container_name: ryrapp
        restart: unless-stopped
        tty: true
        working_dir: /var/www
        volumes:
            - .:/var/www
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
        networks:
            - laravel-network
        depends_on:
            - mysql
            - phpmyadmin

    mysql:
        image: mysql:8.0
        container_name: mysql
        restart: unless-stopped
        tty: true
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravel
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./docker/mysql:/var/lib/mysql
        networks:
            - laravel-network

    mysql_old:
        image: mysql:8.0
        container_name: mysql_old
        restart: unless-stopped
        tty: true
        ports:
            - "3307:3306"
        environment:
            MYSQL_DATABASE: ryr_old
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravel
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./docker/mysql_old:/var/lib/mysql
            - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
        networks:
            - laravel-network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: ryrphpmyadmin
        restart: unless-stopped
        tty: true
        ports:
            - "8081:80"
        environment:
            PMA_ARBITRARY: 1
            PMA_ABSOLUTE_URI: http://localhost:8081/
            UPLOAD_LIMIT: 1024M
            MEMORY_LIMIT: 1024M
            MAX_EXECUTION_TIME: 300
            POST_MAX_SIZE: 1024M
            PHP_UPLOAD_MAX_FILESIZE: 1024M
            PHP_POST_MAX_SIZE: 1024M
            PHP_MEMORY_LIMIT: 1024M
            PHP_MAX_EXECUTION_TIME: 300
        volumes:
            - ./docker/phpmyadmin/php.ini:/usr/local/etc/php/conf.d/php.ini
        depends_on:
            - mysql
            - mysql_old
        networks:
            - laravel-network
    nginx:
        image: nginx:stable-alpine
        container_name: ryrnginx
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel-network


networks:
    laravel-network:
        driver: bridge
